# Generated by Django 4.1.1 on 2022-10-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_course_semester_code_alter_course_course_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_section',
            field=models.CharField(max_length=4),
        ),
    ]
