# Generated by Django 4.1.1 on 2022-11-03 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_book_favorited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favorited_by',
        ),
    ]
