# Generated by Django 4.1.1 on 2022-11-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_course_class_capacity_course_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='meetings_end_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='meetings_start_time',
            field=models.CharField(max_length=50),
        ),
    ]
