# Generated by Django 4.1.1 on 2022-11-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_course_meetings_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.CharField(max_length=10),
        ),
    ]
