# Generated by Django 4.1.1 on 2022-11-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_course_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_available',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
