# Generated by Django 4.1.1 on 2022-12-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_course_enrollment_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
