# Generated by Django 4.1.1 on 2022-12-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_friend_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
