# Generated by Django 4.1.1 on 2022-12-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_delete_friend_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='path/static/website/defaultCover.png', upload_to='images/'),
        ),
    ]
