# Generated by Django 4.1.1 on 2022-12-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='images/defaultCover.png', upload_to='images/'),
        ),
    ]
